### ISSUE TITLE
Develop Slack Platform Hook

### ISSUE THREAD

**Issue by cecilia-sanare** [rain-cafe/flare#1]
### TODO

- [ ] Implement Authentication
- [ ] Implement Message Handler
- [ ] Determine if Command functionality is present on slack
- [ ] Determine if bots can hook into "huddles" in any way
